-- 1. Holiday Management
-- 2. Audit History Structure
--------------------------------------------------------------------------------

-- 1. HOLIDAY MANAGEMENT TABLE
CREATE TABLE PUBLIC_HOLIDAYS (
    holiday_id          NUMBER(10)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date        DATE            NOT NULL UNIQUE,
    description         VARCHAR2(100)   NOT NULL
) TABLESPACE SEC_DATA;

-- Seed Holidays for Dec 2025/Jan 2026 (Upcoming Month)
INSERT INTO PUBLIC_HOLIDAYS (holiday_date, description) VALUES (TO_DATE('2025-12-25', 'YYYY-MM-DD'), 'Christmas Day');
INSERT INTO PUBLIC_HOLIDAYS (holiday_date, description) VALUES (TO_DATE('2025-12-26', 'YYYY-MM-DD'), 'Boxing Day');
INSERT INTO PUBLIC_HOLIDAYS (holiday_date, description) VALUES (TO_DATE('2026-01-01', 'YYYY-MM-DD'), 'New Year Day');
COMMIT;

-- 2. AUDIT LOG TABLE
CREATE TABLE AUDIT_HISTORY (
    audit_id            NUMBER(15)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name          VARCHAR2(30)    NOT NULL,
    operation           VARCHAR2(10)    NOT NULL, -- INS, UPD, DEL
    record_pk           VARCHAR2(100),  -- Primary Key of affected row
    old_value           VARCHAR2(4000), -- Snapshot before change
    new_value           VARCHAR2(4000), -- Snapshot after change
    changed_by          VARCHAR2(50),   -- User who made the change
    change_timestamp    TIMESTAMP       DEFAULT SYSTIMESTAMP
) TABLESPACE SEC_DATA;

-- Index for Audit Performance
CREATE INDEX idx_audit_table ON AUDIT_HISTORY (table_name, change_timestamp) TABLESPACE SEC_IDX;